= JFC - The Java File Extension Cleaner
Mattia Marelli <sesquialtera87@gmail.org>;
v1.0, 2025-03-17

Born from the need to bulk-delete a certain amount of useless files derived from some compilers tools, this simple application show the file-extensions contained into the selected directory to easily remove them.

== Directory selection
A filesystem directory can be specified by choosing one with the file-chooser dialog, by drag-and-drop a folder onto the textfield or simply by typing the path in the textfield.

The textfield offers an autocompletion capability to show all the subdirectories of the current typed path. The textfield has the following hotkeys:

* `CTRL+SPACE`, `TAB` to show the autocompletion popup
* `CTRL+SHIFT+SPACE` to show the full path-history
* `SHIFT+BACKSPACE` to delete the current subdirectory

== Options
Only two simple options are implemented.

* *Use System Trash* By activating this option, you will exploit the `java.awt.Desktop` class and its `moveToTrash` method to remove the selected file and put them into the system trash. This option could be disabled if the trashing capability is not supported by the current system (this is checked with `Desktop.isSupported` method)
* *Recurse in subfolders* With this option the deletion process go down into every subdirectory, searching for the selected extensions and deleting them.

== Installation and run
Actually the application is tested only on Windows and run with a JRE not lower than 17.0.0. The zipped package can be downloaded from the https://github.com/sesquialtera87/JFileCleaner/releases[release page] and could be extracted wherever you want on your local filesystem. The application then can be launched by running the `JFileCleaner.jar` or by using the `exe` provided in the package.
